### ISSUE TITLE
domain(s) hardcoded in account app messages

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#12]
Hi, looking at hp/account/locale/de/LC_MESSAGES/django.po I noticed that jabber.at is hardcoded on
templates/account/user_register.html:27

Please use DEFAULT_XMPP_HOST instead.

**Comment by mathiasertl** [comment]
... I'll fix the issue, but I hope nobody tells you about Twitter Cards or Facebook Opengraph. :-)

**Comment by mathiasertl** [comment]
Fixed in 139ee4de56f4d1c98a342bfce187e7ad0926b5dd. I'm not sure how to fix the meta tags.
