### ISSUE TITLE
wishlist: do not automatically remove superusers

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#16]
ejabberd doesn't know about different types of users and treats them the same, i.e. deleting them after 1 year if you have such a cronjob in place.

celery triggers a daily job that removes accounts from the hp that have been deleted from ejabberd. While it could in theory differentiate between normal and superuser accounts, it currently does not.

Removing superusers automatically is dangeours because all core content they created will be removed as well.

I recommend
- either to differentiate between normal users and superusers and only remove normal accounts automatically
- or make core content independent from their creating superusers
or both.

**Comment by mathiasertl** [comment]
Blogposts and Pages are now no longer deleted when users are removed.

The problem with not removing users is, that:

1. Since they no longer exist on the XMPP server, they cannot log in anyway.
2. The username is effectively "reserved" because they can no longer be registered.
