### ISSUE TITLE
wishlist: make password strength configurable

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#18]
Just noticed after reading "Passwords must be at least six characters." that apparently this is hard-coded and cannot be configured.

**Comment by mathiasertl** [comment]
Damn. The fact that I read the email and didn't check the modified ticket just cost me a few minutes to find just that out ;-)

**Comment by mathiasertl** [comment]
Fixed in d4ef7451cae67c17f4d8f6bce203dc1faed56236. Please also see https://docs.djangoproject.com/ja/1.9/topics/auth/passwords/#enabling-password-validation for configuration.
