### ISSUE TITLE
bug: "REQUIRE_UNIQUE_EMAIL = True" not checked when changing e-mail address

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#19]
Hi,
I have set "REQUIRE_UNIQUE_EMAIL = True", which works for registration, but it can be circumvented by first creating an account with a different address and then using the "change email" function in the account app.

**Comment by mathiasertl** [comment]
I cannot confirm this. The check [here](https://github.com/jabber-at/hp/blob/master/hp/account/views.py#L372-L376) works for me. Can you make sure you use a version that includes those lines? Otherwise can you check on why exactly the if-statement there isn't True?

**Comment by debalance** [comment]
Hm, it's working correctly now, no idea what I did wrong in my test.
