### ISSUE TITLE
Language switcher is using en_b0rken

### ISSUE THREAD

**Issue by schwindp** [jabber-at/hp#2]
https://jabber.at/clients/ shows "View this page in: _Englisch_".

**Comment by mathiasertl** [comment]
It's not really that the language switcher is broken, it's that there isn't really any German content yet, so it defaults to English (what the source language is). The best indicator of your current language is the "About"/"Ueber" button at the very top :-)

**Comment by schwindp** [comment]
Ich meinte ja eher das "Engli_s_ch" (note the extra 's')... :)

**Comment by mathiasertl** [comment]
don't you mean the extra c? ;-)

**Comment by debalance** [comment]
Following that logic, the language switcher should read "Deutsch" when browsing in english, and "English" when browsing in german.

**Comment by mathiasertl** [comment]
That's true. That's what Wikipedia does in their language switcher, e.g. here: https://de.wikipedia.org/wiki/Asienspiele_1951 (random article feature ;-))
