### ISSUE TITLE
bug: server error (500) when trying to use invalid/expired auth tokens

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#21]
When trying to use an invalid/expired auth token,
I get "server error (500)" and an e-mail with the full stack trace to the configured admins.

It would be nice to catch that error.

**Comment by mathiasertl** [comment]
Can you send me the traceback? email = jid!

**Comment by debalance** [comment]
I just did.

**Comment by mathiasertl** [comment]
I don't think I ever got that email. In any case, I did receive similar tracebacks by now.

Is it possible those tracebacks occured with password reset requests only? If yes, the bug is fixed in the last commits :-)

**Comment by debalance** [comment]
Yes, all the tracebacks were from password reset URLs.
