### ISSUE TITLE
social media links are hardcoded

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#3]
Hi,
although localsettings.py.examples contains the block
```
################
# Social media #
################
# Various social media accounts
#FACEBOOK_PAGE = 'example.com'
#TWITTER_HANDLE = 'example_com'
```
these settings seem to have no effect, at least the links in the sidebar are hardcoded.

**Comment by mathiasertl** [comment]
In an added bonus in this commit, you can now also set a Falsy value instead to remove the list items in the sidebar.
