### ISSUE TITLE
wishlist: possibility to enforce unique email addresses

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#7]
I need to restrict users to 1 account per email address, i.e. the email address used for registration must be unique / not registered yet.

Obviously that restriction must also apply to the "Set new email address" feature.

**Comment by mathiasertl** [comment]
Such a restriction must be checked in software. Since I can do either way: Would you like to enforce this in the admin as well?

**Comment by debalance** [comment]
I only need this restriction for end-user registrations, it's okay if admins don't face that restriction, they should know what they're doing.
