### ISSUE TITLE
wishlist: whitelist or regex for allowed email domains

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#8]
I need to restrict the allowed email domains for registration to a specific set.

A whitelist with support for regular expressions would be awesome!

For example
".*foo.net"
".*bar.org"

which would allow all email addresses ending with foo.net or bar.org, including subdomains of foo.net and bar.org

Obviously that restriction must also apply to the "Set new email address" feature.

**Comment by mathiasertl** [comment]
Note that this implementation (during form validation) means that the settings are not enforced in the admin interface. If you are an admin you should know what you're doing, I guess...
