### ISSUE TITLE
bug: DomainWidget not disabled if only 1 domain available

### ISSUE THREAD

**Issue by debalance** [jabber-at/hp#9]
Hi,
according to account/formfields.py line 70, DomainWidget should be disabled if only 1 domain is available, but that doesn't work.

I'm currently using the attached workaround to hardcode that setting in account/widgets.py:
[widgets.py.patch.txt](https://github.com/jabber-at/hp/files/599428/widgets.py.patch.txt)

**Comment by debalance** [comment]
Unfortunately my workaround breaks the login process :(

**Comment by mathiasertl** [comment]
Fixed in 7e2a7d8d2986bb7d9fb657de7181e83e5a6b4116. The issue with my code was, that it didn't actually do anything. 

However setting 'disabled' on a select field doesn't only look nice, it also means that the form value is not submitted. So we add a hidden input field instead.
